name: Yannick Feld
title: Yannick Feld
markdown : kramdown
sass:
    style: compressed
remote_theme: chrisbobbe/jekyll-theme-prologue
theme: jekyll-theme-prologue
collections: [sections]
author: Yannick Feld
email: yannick.feld@uni-oldenburg.de
avatar: assets/images/me.jpg
github_url: https://github.com/Pardoxa
plugins:
  - jekyll-sitemap
exclude:
  - lib/doc/SourceSerifPro-LICENSE.md
