name: Yannick Feld
title: Yannick Feld
markdown : kramdown
sass:
    style: compressed
theme: jekyll-theme-prologue
collections: [sections]
author: Yannick Feld
email: yannick.feld@uni-oldenburg.de
avatar: assets/images/I.jpg
github_url: https://github.com/Pardoxa
